### ISSUE TITLE
All In for Maintainers Launch Plan

### ISSUE THREAD

**Issue by demetris11** [AllInOpenSource/All-In#24]
During the early stages of [All In](allinopensource.org), we learned that maintainers or community leaders really set the tone for inclusion within their respective communities. As such, we wanted to hear from them about what’s working, not working, what challenges persist, and what they would like to see in an eventual program called All In for Maintainers.  

In 2022, we completed the [Maintainers Listening Tour](https://allinopensource.org/community/), which was composed of a series of virtual and in person focus groups and individual interviews, and an online form for asynchronous feedback. We were able to connect with nearly 300 maintainers and community leaders.  Preliminary findings from the listening tour:  [Video](https://www.youtube.com/watch?v=RdwR-E9I3Tg&t=6s), Twitter Thread [part 1](https://twitter.com/dwcheatham/status/1451600372947210240?s=20) and [part 2](https://twitter.com/dwcheatham/status/1451600859922673671)

As a result of the listening tour, we will be launching All In for Maintainers addressing three common pain points shared by many of the maintainers:

1. “Every time someone gives us advice on how to create DEI within our communities, it is often with some long, time consuming process.  We are developers, can’t someone create some automated tools or scripts or something to help us?”
2. “It is overwhelming the number of DEI resources that we receive. We wish there was a website or repo where we could go that has all of those resources in one place.”
3. “Who's doing great work out there with DEI?  What communities or projects?  How can we find them and learn what they are doing?”

**Phase 1**
Anticipated Ship Date:  June 2023 for maintainers month

**_All In/CHAOSS Badging Initiative_** 
_Purpose:_  Recognize projects who have signaled their commitment to DEI with a badge at the repo level

_How it works:_  When a DEI.md file is uploaded to the profile section of any GitHub repo, that rep will automatically receive an All In/CHAOSS badge.
 
_Key Workstream Owners_
- CHAOSS - responsible for drafting templates for the DEI.md file and providing resources that supplements each section of the template. 
- GitHub Communities Team -  responsible for the implementation of the badge being automatically added to the repos.  
- External Vendor - responsible for badge design.  Specs provided by the Communities Team

_Critical Considerations_
- Determine whether the Communities team has the bandwidth to do this or if we will need to procure a contractor for the technical component of this. What’s needed?  

**_All In Grant Program_**
_Purpose:_  Facilitate the creation of freely available tools for maintainers to automate processes that could help increase inclusion within open source communities.

_How it Works:_ GitHub will make $200K available to fund various projects. We will also seek matching funds from companies or foundations with a goal to make $1M available throughout the year. 

_Key Workstream Owners_
Contractor will be responsible for:
- Creation of Request for Proposals and Scoring Rubric
- Need to determine whether generic RFP or specific types of projects that we want funded
- Post launch, organizing an information session and Q&A for potential applicants
- Receiving all proposals
- Grant Selection Committee Management
- Proposing committee members
- Invitation and selection/confirmation
- Communication with grant selection committee
- Convening meetings
- Notification to grant awardees
- Development of expectations document/contract with grant awardees including relevant milestones for grant disbursement
- Grant disbursement logistics 

TIDES Foundation - fiduciary agent for the grant funds

Universities -  potentially identify and help measure impact of DEI tools

Other Foundations or companies - can provide matching funds (initial partner outreach: Ford Foundation, Sloan Foundation, Linux Foundation, Microsoft Research
Others?

_Critical Considerations_
Coordinate with the Product, Communities and other teams in GitHub to make sure we are not duplicating efforts or determine whether there are certain tools that we should be prioritizing based on the needs of the business.

_Part I Key Milestones_
- Launch June 2023 for maintainers month
- The All In/Badge should be ready to go at this time
- The Grant Program application will be made available
- Grant awardees announced - TBD
- TBD -  when projects need to be finished 

**Phase 2** (in development)
Anticipated Ship Date:  January/February 2023

**_Central Hub for DEI Resources_**

_Purpose:_  Create a central repository for vetted DEI resources for maintainers to easily search and access.

_How it works:_  Very similar in model to [https://resources.github.com/] (https://resources.github.com/).  A place in which links to DEI from various organizations throughout open source can be found as well as opportunities for original content creation, similar to [www.opensource.com](http://www.opensource.com/).

**We welcome feedback and suggestions on how to make this initiative more impactful!**

**Comment by germonprez** [comment]
In the CHAOSS DEI WG, we asked a few questions regarding the program and I thought I would share them here to help define the program: 

What we are aiming to accomplish with the current program?
- This project aims to have communities become educated on particular DEI metrics and share that effort with community members. 
- The DEI Badging Programs makes an effort towards centering DEI within open source projects. 
- The DEI BP helps educate communities on things to consider in centering DEI in their projects. 

The future goals of the program
- Trying to improve DEI across open source by including community members in the reflection, presentation, and discussion process. Open sourcing DEI where we can all have an input and say how DEI is centered within our open source projects. More than just a code of conduct. 
- To continue to sustain and grow how we center DEI beyond the CoC. 

Text that describes what this badge is signaling. This is really important, particularly as we are using an automated process in the first phase of Project Badging. 
- It signals an interest in centering DEI and a willingness to learn and willingness to open source this conversation within your community. 
- Gives projects an opportunity to bring visibility to their own unique efforts.

**Comment by jwflory** [comment]
Hi, I also learned of this discussion from the CHAOSS D.E.I. working group. I support the effort to provide tools and recognition to maintainers for better centering diversity, equity, and inclusion in their projects and communities. 🙌🏻 💯 

> Purpose: Recognize projects who have signaled their commitment to DEI with a badge at the repo level
>
> How it works: When a DEI.md file is uploaded to the profile section of any GitHub repo, that rep will automatically receive an All In/CHAOSS badge.

Before rolling this feature out to all GitHub users, I see a potential safety & abuse concern if a repository maintainer uses this feature in a harmful way and receives recognition via a badge. A maintainer could upload a `DEI.md` file with exclusive, discrimantory, and/or racist content. A remedy could be a closer first review of what content is shared back by GitHub maintainers. Two possible mitigations would be improved documentation for D.E.I. in Open Source (which is addressed in this proposal, but at a later stage) and working with a small pilot group (e.g. @maintainers) to trial this feature with a small group of GitHub users who maintain popular GitHub projects. This could add a useful round of feedback by a key user group of developer advocates from across GitHub before the feature goes out to all users.

> Purpose: Create a central repository for vetted DEI resources for maintainers to easily search and access.

Does the All In team have capacity to support Cross Community Collaboration around this deliverable? The need for common and up-to-date information about vetted DEI resources is a shared need by many communities, including some I participate with (e.g. [OpenSourceDiversity.org](https://opensourcediversity.org/) and [Fedora D.E.I. Team](https://docs.fedoraproject.org/en-US/diversity-inclusion/)). A challenge we experienced was finding a "maintainer" (or Product Owner) who could support with ongoing program management together with a distributed group of volunteers, collaborating on shared resources similar to the Central Hub for DEI Resources proposed here. An engaged community of practice could also assist in editing and maintaining this information on an ongoing basis.

I would be all in to participate in a community of practice around this 😃

**Comment by germonprez** [comment]
Hi everyone, 

I thought I'd share the current form of the DEI.md file. Thanks to the input from Kevin Lumbard and Nikki Stevens. 

DEI Review Statement

[project name] prioritizes and reflects on DEI through a regular review of project policies and performance based on [CHAOSS best practices for DEI](…). [Project name] has reflected on DEI related to:

-       [Newcomer Experiences](…)
-       [Project Burnout]( https://chaoss.community/metric-project-burnout/)
-       [Recognizing Contributors]( https://chaoss.community/metric-contributors/)
-       [Inclusive Leadership]( https://chaoss.community/metric-inclusive-leadership/)

[Project name] is We recognize that the inclusion of the DEI.md file and the provided reflection on the four metrics does not ensure community safety nor community inclusiveness. The inclusion of the DEI.md file signals that we are committed to continually improving ourits DEI by regularly reviewing and reflecting on our project DEI practices in line with [CHAOSS best practices for DEI](...), and on a regular n annual basis, updating this statement and project policies in-line with the review findings.

If you do not feel that the DEI.md file appropriately addresses concerns you have about community safety and inclusiveness, please let us know. You can do this by checking out our Code of Conduct (link) to raise concerns you have with the Code of Conduct team. 

Last Reviewed: [Enter Date]

**Comment by germonprez** [comment]
There was also an idea to have any recognition expire in some time frame (1 year?)

**Comment by soyetubo** [comment]
Meeting notes and action items from the October 3, 2022 sync can be found [here](https://docs.google.com/document/d/1gFjXoBx0zZ2qqlAmfkDG7zmr6yXKoaLMJxbsedAfMrQ/edit#).
