### ISSUE TITLE
Can't subscribe as Individual Contributor on website

### ISSUE THREAD

**Issue by MartijnVisser** [AllInOpenSource/All-In#26]
When filling in the form at https://allinopensource.org/become-a-partner/, selecting `Individual Contributor` and submitting the form, an error is displayed since the mailing list subscription form from Mailchimp doesn't accept this as an option

<img width="695" alt="image" src="https://user-images.githubusercontent.com/2989614/194149259-a816c7f2-4769-4165-8f50-f5fb2eeb2069.png">

**Comment by soyetubo** [comment]
Thank you for sharing this @MartijnVisser! Our team is working on fixing this issue as I write you. I will follow-up once this has been completed.

**Comment by soyetubo** [comment]
@MartijnVisser thank you once again for raising this to our attention. The error has been fixed, and you are now able to submit your response to the ["Become a Partner" form](https://allinopensource.org/become-a-partner/).

**Comment by MartijnVisser** [comment]
@soyetubo Thanks, I can confirm it works again :)
