### ISSUE TITLE
Applications for micro-mentoring at GitHub Universe 2022 

### ISSUE THREAD

**Issue by soyetubo** [AllInOpenSource/All-In#27]
Request from @toyae to invite the 2022 All In for Students cohort to sign up for the [Micro-Mentoring at GitHub Universe 2022 session](https://github.blog/2022-09-21-applications-for-micro-mentoring-at-github-universe-2022-are-now-live/).

Requested ship date: October 5, 2022

Email recipients:
- All In for Students 2022 University Partners
-  All In for Students 2022 Cohort

-----

### Copy for University Partners

Dear University Partners,

GitHub is excited to announce an opportunity for students at your university to connect with employees at GitHub ahead of [GitHub Universe 2022](https://github.blog/2022-08-31-what-you-can-expect-at-github-universe-2022-cloud-security-community-and-ai)! This year, the conference will take place virtually and in person, November 9-10, and to kick the week off, we’re thrilled to host virtual [Micro-Mentoring sessions](https://github.blog/2022-09-21-applications-for-micro-mentoring-at-github-universe-2022-are-now-live/).

The Micro-Mentoring session allows students to participate in a 30-minute, 1:1 mentoring and networking session with GitHub employees and will take place over a course of two days: Monday, November 7, 2022 and November 8, 2022 between 4:00 am-10:30 am PT (7:00 am-1:30 pm ET).

The Micro-Mentoring sessions will cover the following topics:
Day 1 - November 7, 2022: Resume Review
Day 2 - November 8, 2022: Technical Career Pathing

Students interested in participating in this event can sign up for one session for either of the tracks listed above.

How to take part:

Please direct the students to use [this link](https://forms.gle/yN4ESWqeKKKRfQYj9) to apply.
A diverse team of GitHub employees will review each application.
Applications must be received by 5:00 pm PT Friday, October 7.
You must be 18 or older and currently enrolled in a college/university/academic institution.
If you are selected to participate, we will contact you by email by Wednesday, October 12, and you must confirm your attendance in writing by email by Monday, October 17.
To learn more about the micro-mentoring session, check out the [GitHub blog post](https://github.blog/2022-09-21-applications-for-micro-mentoring-at-github-universe-2022-are-now-live/) for more details.

Regards,

Sarah Oyetubo

### Copy for Students 

Hello All In for Students 2022 Cohort,

We have an exciting opportunity for you to connect with employees at GitHub ahead of [GitHub Universe 2022](https://github.blog/2022-08-31-what-you-can-expect-at-github-universe-2022-cloud-security-community-and-ai)! This year, the conference will take place virtually and in person November 9-10, and to kick the week off, we’re thrilled to host a virtual [Micro-Mentoring session](https://github.blog/2022-09-21-applications-for-micro-mentoring-at-github-universe-2022-are-now-live/). 

The Micro-Mentoring session allows select students to participate in a 30-minute, 1:1 mentoring and networking session with GitHub employees and will take place over a course of two days: Monday, November 7, 2022 and November 8, 2022 between 4:00 am-10:30 am PT (7:00 am-1:30 pm ET).

The Micro-Mentoring sessions will cover the following topics:
Day 1 - November 7, 2022: Resume Review
Day 2 - November 8, 2022: Technical Career Pathing

Students interested in participating in this event can sign up for one session for either of the tracks listed above.

How to take part:
Please use [this link](https://docs.google.com/forms/d/e/1FAIpQLSeyM5YKRduHRSOzl1bo5A9drR450W6CI8-40K9_SR-dB7BisQ/viewform) to apply.
A diverse team of GitHub employees will review each application.
Applications must be received by 5:00 pm PT Friday, October 7
You must be 18 or older and currently enrolled in a college/university/academic institution.
If you are selected to participate, we will contact you by email by Wednesday, October 12, and you must confirm your attendance in writing by email by Monday, October 17.

To learn more about the micro-mentoring session, check out the [GitHub blog post](https://github.blog/2022-09-21-applications-for-micro-mentoring-at-github-universe-2022-are-now-live/) for more details. And please feel free to share this invitation with your peers.

Regards,

Sarah Oyetubo

-----
cc: @toyae @camaleyjennings1 @demetris11

**Comment by soyetubo** [comment]
@camaleyjennings1 has reviewed and approved the copy to ship

**Comment by soyetubo** [comment]
Both emails have shipped 🚢  - @toyae and @camaleyjennings1

**Comment by camaleyjennings1** [comment]
Thank you @soyetubo!!
