### ISSUE TITLE
Fix broken link on DEI Project Badging page

### ISSUE THREAD

**Issue by Ruth-ikegah** [AllInOpenSource/All-In#37]
Bug: We moved the file for the DEI.md file from this repository to the Project Badging repository, so the link is broken on [this page](https://allinopensource.org/maintainers/DEI-badging/).

Implementation: Fix the broken link in the last paragraph "We are currently asking for feedback on this DEI.md file and for volunteers to not only help us build future DEI-related metrics, but to take part in the DEI Badging Limited Pilot Program.

New link to replace: https://github.com/AllInOpenSource/ProjectBadging/blob/main/DEI.md

**Comment by soyetubo** [comment]
Thank you for flagging! This is now fixed.
